export const siteConfig = {
  name: "Chase Portraits Photography",
  shortName: "Chase Portraits",
  phone: "615-933-1169",
  email: "chaseportraits@gmail.com",
  location: "LaVergne, TN 37086",
  social: {
    facebook: "https://facebook.com/chaseportraits",
    instagram: "https://instagram.com/chase_portraits",
  },
  hours: [
    { days: "Monday - Friday", time: "9:00 AM - 6:00 PM" },
    { days: "Saturday", time: "9:00 AM - 8:00 PM" },
    { days: "Sunday", time: "12:00 PM - 6:00 PM" },
  ],
};

export const navLinks = [
  { label: "Home", href: "/" },
  { label: "Services", href: "/services" },
  { label: "Portfolio", href: "/portfolio" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const testimonials = [
  {
    name: "Lastasha Mcbee",
    quote: "Chase is a fantastic photographer. I highly recommend Chase Portraits.",
    rating: 5,
  },
  {
    name: "Elizabeth Ham",
    quote: "Personable and fun to work with",
    rating: 5,
  },
  {
    name: "Krystle",
    quote: "Provided wonderful experience! Professional yet relaxed. Amazing shots.",
    rating: 5,
  },
];

export const portraitPackages = [
  {
    name: "Basic",
    price: 300,
    duration: "1 hour",
    images: 8,
    outfits: "1 outfit",
    popular: false,
    features: [
      "1 hour photo session",
      "8 fully retouched images",
      "Online gallery with downloads",
      "Print release",
      "Mobile photo app",
    ],
  },
  {
    name: "Deluxe",
    price: 375,
    duration: "1.5 hours",
    images: 16,
    outfits: "2 outfits",
    popular: true,
    features: [
      "1.5 hour photo session",
      "16 fully retouched images",
      "Online gallery with downloads",
      "Print release",
      "Mobile photo app",
    ],
  },
  {
    name: "Premium",
    price: 550,
    duration: "2 hours",
    images: 25,
    outfits: "Unlimited outfits",
    popular: false,
    features: [
      "2 hour photo session",
      "25 fully retouched images",
      "Online gallery with downloads",
      "Print release",
      "Mobile photo app",
    ],
  },
];

export const weddingPackages = [
  {
    name: "Intimate Ceremony",
    price: 750,
    duration: "2-3 hours",
    description: "Ceremony and couple portraits",
    features: ["2-3 hours coverage", "Ceremony + couple portraits", "Digital gallery"],
  },
  {
    name: "Modern Wedding",
    price: 2000,
    duration: "5 hours",
    description: "Ceremony through portraits",
    features: ["5 hours coverage", "Ceremony + portraits", "Reception details", "Digital gallery"],
  },
  {
    name: "Elegant Wedding",
    price: 2500,
    duration: "8 hours",
    description: "Full ceremony and reception",
    features: ["8 hours coverage", "Ceremony + portraits", "Reception details + coverage", "Digital gallery"],
  },
  {
    name: "Luxury Wedding",
    price: 3500,
    duration: "10 hours",
    description: "Complete coverage with album",
    features: [
      "10 hours coverage",
      "Ceremony + portraits",
      "Reception details + full coverage",
      "Complimentary 10x10 album",
      "Digital gallery",
    ],
  },
];

export const eventInfo = {
  rate: "$200/hour",
  minimumHours: 2,
  types: ["Birthdays", "Anniversaries", "Church services", "Graduations", "Ceremonies", "Parties", "Shows"],
  addOns: [
    { name: "Rush delivery", price: "$75-$100" },
    { name: "Extended hours", price: "$150/hour" },
  ],
};

export const faqItems = [
  {
    question: "What are your business hours?",
    answer: "We are available Monday through Friday from 9:00 AM to 6:00 PM, Saturdays from 9:00 AM to 8:00 PM, and Sundays from 12:00 PM to 6:00 PM.",
  },
  {
    question: "How do I book a session?",
    answer: "Browse our services, contact us to discuss your preferences, select a location and date, and choose a package. A 50% non-refundable deposit is required to secure your booking.",
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept Visa, Mastercard, and debit/credit cards via invoice.",
  },
  {
    question: "How many photos will I receive?",
    answer: "The number of edited images depends on your package, ranging from 8 to 25+ retouched images for portrait sessions, and 40-60 edited images per hour for events.",
  },
  {
    question: "Do you provide raw files?",
    answer: "No, we only deliver professionally edited images. Raw files are not included in any package.",
  },
  {
    question: "What is your cancellation/refund policy?",
    answer: "The 50% deposit is non-refundable. Rescheduling is available with at least 48 hours notice.",
  },
];

export const portraitGallery = [
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_0022-Edit.jpg", alt: "Portrait session" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_0431.jpg", alt: "Portrait photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1599-2.jpg", alt: "Portrait session" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2161.jpg", alt: "Portrait photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2386.jpg", alt: "Portrait session" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2397.jpg", alt: "Portrait photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2616.jpg", alt: "Portrait session" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4659-Edit.jpg", alt: "Portrait photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4682-Edit-2.jpg", alt: "Portrait session" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4817.jpg", alt: "Portrait photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4824.jpg", alt: "Portrait session" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_5085-Edit-2.jpg", alt: "Portrait photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6311.jpg", alt: "Portrait session" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_7395.jpg", alt: "Portrait photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_7827.jpg", alt: "Portrait session" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_8166-Edit-66f04519.jpg", alt: "Portrait photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_8192-Edit-7d87becc.jpg", alt: "Portrait session" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_8503.jpg", alt: "Portrait photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9733.jpg", alt: "Portrait session" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9872.jpg", alt: "Portrait photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9906-Edit.jpg", alt: "Portrait session" },
];

export const weddingGallery = [
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_0912.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1014.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1057-Edit.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1077.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1112.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1208.jpg", alt: "Wedding reception" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1224.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1241.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1263.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1304.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1314.jpg", alt: "Wedding reception" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1343.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1364.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1382.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1443.jpg", alt: "Wedding reception" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1514.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1524.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1544.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1578.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1647.jpg", alt: "Wedding reception" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1674.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1714.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1859.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2238.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2256.jpg", alt: "Wedding reception" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2578.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2648.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2655.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4499.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4649.jpg", alt: "Wedding reception" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4662.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4962.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_5048.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_5860-2.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_5934.jpg", alt: "Wedding reception" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6017.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6039.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6053.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6121.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6170.jpg", alt: "Wedding reception" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6248.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6278.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_7178.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_7185.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_7707.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_7835.jpg", alt: "Wedding reception" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_8682.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9364-Edit.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9532.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9602.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9636.jpg", alt: "Wedding reception" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9705.jpg", alt: "Wedding portraits" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9738.jpg", alt: "Wedding ceremony" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9821.jpg", alt: "Wedding photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9869.jpg", alt: "Wedding reception" },
];

export const eventGallery = [
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_0736.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_0742.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_0753.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_0769.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_0910.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1415.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1588.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_1839.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2157.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2340.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2392.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_2398.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4591.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4592.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4597.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4599.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_4625.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_5716.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_5717.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_5721.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_5969.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6013.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6015.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6191.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6298.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6526.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6631.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6685.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6697.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_6699.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_7998.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_8002.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_8018.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_8021.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_8024.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9021.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9104.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9200.jpg", alt: "Event coverage" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9347.jpg", alt: "Event photography" },
  { src: "https://irp.cdn-website.com/fe9bd626/dms3rep/multi/IMG_9381.jpg", alt: "Event coverage" },
];
